# Generated by Django 4.2.4 on 2023-08-04 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='')),
                ('is_liked', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=100)),
                ('location', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='events.locations')),
            ],
        ),
    ]
